name: deploy to xserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: ssh key generate
          run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        - name: rsync deployments
          uses: burnett01/rsync-deployments@5.1
          with:
            switches: -avz --delete
            path: dist/
            remote_path: /home/sushiboys350/sushiboys350.com/public_html/
            remote_host: sv13281.xserver.jp
            remote_user: sushiboys350
            remote_port: 10022
            remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
